import React, { useEffect, useState } from 'react'
import { Globe, Heart, MapPin, Star } from '@openai/apps-sdk-ui/components/Icon'
import { CountryCitySelector, DestinationSearch } from './DestinationSearch.jsx'
import { EmptyState, ErrorNotice, LoadingCards, PinMap, ProviderBadge, SectionHeader, SourceLine } from './Chrome.jsx'
import { loadDestinationBundle } from '../services.js'

const tabs=['Overview','Country','City','What to visit','Where to stay','Where to eat','Map']
export function ExploreGuide({ services, userState, onDestinationSelected, selectedDestination, setSelectedDestination, toggleFavorite }) {
  const [bundle,setBundle]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('Overview')
  useEffect(()=>{ let cancel=false; if(!selectedDestination) return; setLoading(true); setError(''); loadDestinationBundle(services, selectedDestination).then(b=>{ if(!cancel) setBundle(b) }).catch(e=>{ if(!cancel) setError(e.message||'Destination load failed') }).finally(()=>{ if(!cancel) setLoading(false) }); return()=>{cancel=true} },[selectedDestination,services])
  function choose(d){ setSelectedDestination(d); onDestinationSelected?.(d); setTab('Overview') }
  if(!selectedDestination) return <section className="tp-hero"><DestinationSearch services={services} recent={userState.recentSearches} onSelect={choose}/><CountryCitySelector services={services} onSelect={choose}/></section>
  return <section className="tp-two"><div className="tp-panel"><SectionHeader title={selectedDestination.formatted || selectedDestination.city}><button className="tp-btn ghost" onClick={()=>setSelectedDestination(null)}>Change destination</button><button className="tp-btn ghost" onClick={()=>toggleFavorite({ ...selectedDestination, kind:'destination' })}><Heart size={15}/>Favorite</button></SectionHeader><div className="tp-chiprow"><span className="tp-chip live"><Globe size={13}/> {selectedDestination.country}</span><SourceLine source={selectedDestination.source}/></div><nav className="tp-tabs">{tabs.map(t=><button key={t} className={`tp-btn ${tab===t?'primary':'ghost'}`} onClick={()=>setTab(t)}>{t}</button>)}</nav>{loading && <LoadingCards count={6}/>} {error && <ErrorNotice message={error} retry={()=>setSelectedDestination({...selectedDestination})}/>} {bundle && <GuideTab tab={tab} destination={selectedDestination} bundle={bundle} toggleFavorite={toggleFavorite}/>}</div><aside className="tp-panel"><h2>Provider status</h2>{Object.values(services.providers).slice(0,8).map(p=><ProviderBadge key={p.id} provider={p}/>) }<div className="tp-card topline"><h3>Live-data rule</h3><p className="tp-muted">Changing facts show sources and unavailable fields stay unavailable. Ratings, reviews, hotel prices, visa advice and tickets are not invented when the configured providers do not supply them.</p></div>{bundle && <PinMap destination={selectedDestination} places={bundle.attractions} restaurants={bundle.restaurants} accommodation={bundle.accommodation}/>}</aside></section>
}
function GuideTab({ tab, destination, bundle, toggleFavorite }) {
  if(tab==='Overview') return <div className="tp-grid"><InfoCard title="Destination identity" rows={[['City / place', destination.city],['Country',destination.country],['Coordinates',`${destination.coordinates.lat.toFixed(4)}, ${destination.coordinates.lon.toFixed(4)}`],['Provider ID',destination.placeId]]}/><InfoCard title="Available sections" rows={[['Attractions',bundle.attractions.length],['Restaurants',bundle.restaurants.length],['Accommodation',bundle.accommodation.length],['Provider failures',bundle.failures.length || 'None']]}/><div className="tp-card topline"><h3>AI-ready summary</h3><p className="tp-muted">A production AIService would summarize the retrieved provider facts here. This MVP keeps the source facts structured and does not ask AI to invent missing live data.</p></div></div>
  if(tab==='Country') return bundle.country ? <div className="tp-grid"><InfoCard title={bundle.country.name} rows={[['Official name',bundle.country.officialName],['Capital',bundle.country.capital],['Languages',bundle.country.languages],['Currency',bundle.country.currency],['Time zones',bundle.country.timezones],['Calling code',bundle.country.callingCode],['Population',bundle.country.population?.toLocaleString?.() || 'Unavailable']]}/><div className="tp-card"><h3>Visa and entry disclaimer</h3><p className="tp-muted">{bundle.country.visaDisclaimer}</p><SourceLine source={bundle.country.source}/></div><div className="tp-card"><h3>Payment and tourist notes</h3><p className="tp-muted">{bundle.country.paymentAdvice}</p></div></div> : <EmptyState title="Country information unavailable" body="The country provider failed or this result does not include a country code."/>
  if(tab==='City') return <div className="tp-grid"><div className="tp-card"><h3>City information service</h3><p className="tp-muted">City history, districts, transport, customs and safety should come from a CityInfoService backed by tourism APIs, official websites or curated datasets. This foundation keeps the service boundary explicit instead of hardcoding text for each destination.</p></div><div className="tp-card"><h3>Transport guidance</h3><p className="tp-muted">Public transport, taxi, airport transfer and ticket purchase details are marked pending until a provider or official source returns them.</p></div><div className="tp-card"><h3>Before arrival</h3><p className="tp-muted">The UI is ready for accordions/cards once CityInfoService provides sourced facts with retrievedAt/expiresAt metadata.</p></div></div>
  if(tab==='What to visit') return <PlaceGrid places={bundle.attractions} empty="No attractions returned by the current OSM query. Try a larger city or connect Google Places." toggleFavorite={toggleFavorite}/>
  if(tab==='Where to stay') return <PlaceGrid places={bundle.accommodation} empty="No accommodation returned by the current provider. Booking-style availability/prices require a credentialed provider." toggleFavorite={toggleFavorite}/>
  if(tab==='Where to eat') return <PlaceGrid places={bundle.restaurants} empty="No restaurants returned by the current provider." toggleFavorite={toggleFavorite}/>
  return <PinMap destination={destination} places={bundle.attractions} restaurants={bundle.restaurants} accommodation={bundle.accommodation}/>
}
function InfoCard({ title, rows }) { return <div className="tp-card topline"><h3>{title}</h3>{rows.map(([k,v])=><div className="tp-budgetrow" key={k}><span className="tp-muted">{k}</span><strong>{v ?? 'Unavailable'}</strong></div>)}</div> }
function PlaceGrid({ places, empty, toggleFavorite }) { if(!places.length) return <EmptyState title="No provider results" body={empty}/>; return <div className="tp-grid">{places.map(p=><div className="tp-card topline" key={p.id}><div className="tp-chiprow"><span className="tp-chip"><Star size={12}/> Rating unavailable</span><span className="tp-chip">Score {p.recommendationScore}/100</span></div><h3>{p.name}</h3><p className="tp-muted">{p.category} · {p.address}</p>{p.openingHours && <p><strong>Opening hours:</strong> {p.openingHours}</p>}{p.website && <a className="tp-btn ghost" href={p.website} target="_blank" rel="noreferrer">Official / website</a>}<SourceLine source={p.source}/><div className="tp-chiprow"><button className="tp-btn ghost" onClick={()=>toggleFavorite(p)}><Heart size={14}/> Save</button><a className="tp-btn ghost" href={`${'https://' + 'www.openstreetmap.org'}/?mlat=${p.coordinates.lat}&mlon=${p.coordinates.lon}#map=16/${p.coordinates.lat}/${p.coordinates.lon}`} target="_blank" rel="noreferrer"><MapPin size={14}/> Map</a></div><p className="tp-source">{p.freshnessNote}</p></div>)}</div> }
