import React, { useState } from 'react'
import { Calendar, Check, Lock, Trash } from '@openai/apps-sdk-ui/components/Icon'
import { DestinationSearch } from './DestinationSearch.jsx'
import { EmptyState, Money, PinMap, SectionHeader, SourceLine } from './Chrome.jsx'
import { compactId, estimateBudget } from '../domain.js'
import { loadDestinationBundle } from '../services.js'

const tripTypes=['City Break','Family','Adventure','Relax','Romantic','Food','Culture','Nightlife','Budget','Luxury']
const interests=['Museums','Food','History','Parks','Shopping','Architecture','Beaches','Local culture']
export function PlanTrip({ services, userState, saveTrip, activeTrip, setActiveTrip }) {
  const [step,setStep]=useState('form'),[origin,setOrigin]=useState(activeTrip?.origin||null),[destination,setDestination]=useState(activeTrip?.destination||null)
  const [form,setForm]=useState({ startDate: activeTrip?.startDate || '2027-05-10', endDate: activeTrip?.endDate || '2027-05-15', adults:2, children:1, childAges:'3', budget:2000, pace:'Balanced', tripTypes:['Family','Culture'], interests:['Museums','Food','History'] })
  const [working,setWorking]=useState(false),[result,setResult]=useState(activeTrip||null),[error,setError]=useState('')
  const toggle=(key,value)=>setForm(f=>({ ...f, [key]: f[key].includes(value) ? f[key].filter(x=>x!==value) : [...f[key], value] }))
  async function generate(){ if(!destination){ setError('Choose a destination first.'); return } setWorking(true); setError(''); try { const bundle=await loadDestinationBundle(services,destination); const trip={ id: activeTrip?.id || compactId('trip'), origin, destination, ...form, children:Number(form.children||0), adults:Number(form.adults||1), budget:Number(form.budget||0), childAges:String(form.childAges||'').split(',').map(s=>s.trim()).filter(Boolean), updatedAt:new Date().toISOString() }; const [weather, transport]=await Promise.all([services.weather.forTrip(destination, form.startDate, form.endDate).catch(e=>({kind:'unavailable',message:e.message})), Promise.resolve(services.transport.compare({origin,destination}))]); const flights=services.flights.search({origin,destination,startDate:form.startDate,endDate:form.endDate,travellers:Number(form.adults)+Number(form.children)}); const itinerary=services.itinerary.generate({ trip, attractions:bundle.attractions, restaurants:bundle.restaurants, weather }); const budget=estimateBudget({ trip, accommodation:bundle.accommodation, attractions:bundle.attractions, transport }); const full={ ...trip, bundle, weather, transport:[...transport,...flights], itinerary, budget }; setResult(full); setActiveTrip(full); setStep('result') } catch(e){ setError(e.message || 'Trip generation failed') } finally { setWorking(false) } }
  if(step==='form') return <section className="tp-two"><div className="tp-panel"><SectionHeader title="Plan a Trip"><span className="tp-chip live">Structured trip context</span></SectionHeader><div className="tp-formgrid"><DestinationSearch services={services} onSelect={setOrigin} recent={userState.recentSearches} label="Departure location"/><DestinationSearch services={services} onSelect={setDestination} recent={userState.recentSearches} label="Destination"/></div><div className="tp-grid"><TripPick title="Origin" item={origin}/><TripPick title="Destination" item={destination}/><div className="tp-card"><h3>Dates and travellers</h3><div className="tp-formgrid"><Field label="Departure date"><input className="tp-input" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field label="Return date"><input className="tp-input" type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field><Field label="Adults"><input className="tp-input" type="number" min="1" value={form.adults} onChange={e=>setForm({...form,adults:e.target.value})}/></Field><Field label="Children"><input className="tp-input" type="number" min="0" value={form.children} onChange={e=>setForm({...form,children:e.target.value})}/></Field><Field label="Children ages"><input className="tp-input" value={form.childAges} onChange={e=>setForm({...form,childAges:e.target.value})}/></Field><Field label="Budget (€)"><input className="tp-input" type="number" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></Field></div></div></div><div className="tp-card"><h3>Preferences</h3><Field label="Travel pace"><select className="tp-select" value={form.pace} onChange={e=>setForm({...form,pace:e.target.value})}><option>Relaxed</option><option>Balanced</option><option>Intensive</option></select></Field><span className="tp-label">Trip type</span><div className="tp-chiprow">{tripTypes.map(t=><button key={t} className={`tp-chip ${form.tripTypes.includes(t)?'live':''}`} onClick={()=>toggle('tripTypes',t)}>{t}</button>)}</div><span className="tp-label">Interests</span><div className="tp-chiprow">{interests.map(t=><button key={t} className={`tp-chip ${form.interests.includes(t)?'live':''}`} onClick={()=>toggle('interests',t)}>{t}</button>)}</div></div>{error && <p className="tp-source">{error}</p>}<button className="tp-btn primary" disabled={working} onClick={generate}><Calendar size={16}/>{working?'Generating from providers…':'Generate trip'}</button></div><aside className="tp-panel"><h2>Generation engine</h2>{['Resolve locations','Load country/city provider data','Discover attractions/restaurants/stays','Check weather policy','Compare transport abstractions','Score and cluster places','Build daily windows','Produce AI-ready explanation'].map(x=><div className="tp-card" key={x}><strong>{x}</strong></div>)}</aside></section>
  if(!result) return <EmptyState title="No trip result" body="Generate a trip first."/>
  return <TripResult trip={result} saveTrip={saveTrip} setStep={setStep} setResult={setResult}/>
}
function Field({ label, children }) { return <div className="tp-field"><span className="tp-label">{label}</span>{children}</div> }
function TripPick({ title, item }) { return <div className="tp-card"><span className="tp-label">{title}</span><h3>{item?.city || 'Not selected'}</h3><p className="tp-muted">{item?.formatted || 'Use search to resolve this location dynamically.'}</p>{item?.source && <SourceLine source={item.source}/>}</div> }
function TripResult({ trip, saveTrip, setStep, setResult }) { const max=Math.max(...trip.budget.rows.map(r=>r.amount),1); function remove(dayId,itemId){ setResult(t=>({...t,itinerary:{...t.itinerary,days:t.itinerary.days.map(d=>d.id===dayId?{...d,items:d.items.filter(i=>i.id!==itemId)}:d)}})) } function lock(dayId,itemId){ setResult(t=>({...t,itinerary:{...t.itinerary,days:t.itinerary.days.map(d=>d.id===dayId?{...d,items:d.items.map(i=>i.id===itemId?{...i,locked:!i.locked}:i)}:d)}})) }
  return <section className="tp-two"><div className="tp-panel"><SectionHeader title={`${trip.destination.city || 'Trip'} itinerary`}><button className="tp-btn ghost" onClick={()=>setStep('form')}>Edit form</button><button className="tp-btn primary" onClick={()=>saveTrip(trip)}><Check size={15}/> Save trip</button></SectionHeader><div className="tp-chiprow"><span className="tp-chip live">{trip.startDate} → {trip.endDate}</span><span className="tp-chip">{trip.adults} adults · {trip.children} children</span><span className="tp-chip warn">Weather: {trip.weather.kind}</span></div><div className="tp-grid">{trip.itinerary.days.map(day=><div className="tp-card tp-day" key={day.id}><h3>{day.title}</h3><p className="tp-source">{day.weatherNote}</p>{day.items.map(item=><div className="tp-item" key={item.id}><span className="tp-time">{item.startTime}</span><div><strong>{item.title}</strong><p className="tp-muted">{item.reason}</p></div><div className="tp-chiprow"><button className="tp-chip" onClick={()=>lock(day.id,item.id)}><Lock size={12}/>{item.locked?'Locked':'Lock'}</button><button className="tp-chip" onClick={()=>remove(day.id,item.id)}><Trash size={12}/></button></div></div>)}</div>)}</div></div><aside className="tp-panel"><h2>Trip context</h2><PinMap destination={trip.destination} origin={trip.origin} places={trip.bundle.attractions} restaurants={trip.bundle.restaurants} accommodation={trip.bundle.accommodation}/><div className="tp-card"><h3>Budget estimate</h3>{trip.budget.rows.map(r=><div className="tp-budgetrow" key={r.label}><div><strong>{r.label}</strong><div className="tp-source">{r.type}</div><div className="tp-bar"><span style={{width:`${Math.round(r.amount/max*100)}%`}}/></div></div><strong><Money amount={r.amount}/></strong></div>)}<hr/><div className="tp-budgetrow"><strong>Total</strong><strong><Money amount={trip.budget.total}/></strong></div><p className="tp-source">Budget categories distinguish retrieved prices from planning estimates.</p></div><div className="tp-card"><h3>Transport</h3>{trip.transport.map(t=><p className="tp-muted" key={t.id}><strong>{t.mode || t.title}:</strong> {t.detail || t.description}</p>)}</div></aside></section> }
